select * from customer limit 20

-- 1. What is the total revenue generated by male vs female customers ? 
select gender, SUM(purchase_amount)as revenue
from customer
group by gender

-- 2. Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- 3. Which are top 5 products with the highest average review rating?
-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- 5. Do subscribed customers spend more? Compare average spend and toatal revenue between subscribers and non-subscribers.